import type { Metadata } from "next";
import "./globals.css";
import CustomCursor from "@/app/components/CustomCursor"; // Asegúrate de que la ruta sea correcta

export const metadata: Metadata = {
  title: "Portfolio Pau Melià 2024",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}
