import type { Metadata } from "next";

import "./globals.css";



export const metadata: Metadata = {
  title: "Portfolio Pau Melià 2024",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body >{children}</body>
    </html>
  );
}
